name: Build and deploy WAR app to Azure Web App - TechblogSanjay

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Apache Ant
        uses: apache/ant-setup-action@v1.1.0 # unofficial, or install manually if needed

      - name: Build with Ant
        run: ant clean build
        # assumes your build.xml is in project root
        # and produces a WAR file inside a `dist/` or `build/` directory

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '**/*.war'  # adjust if your WAR is in a specific folder

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FE3B4565DAEB437F94FD94CB934FB3C1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55A51041D9694594A298F6217442D30D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_27D4A114A01247CB9957EDE6C6F29D51 }}

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: 'TechblogSanjay'
      #     slot-name: 'Production'
      #     package: '*.war'
